# Generated by Django 4.2.4 on 2023-09-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestyle',
            name='values',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lifestyle',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
