# Generated by Django 4.2.4 on 2023-09-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_body_options_alter_body_arm_chest_and_more'),
        ('diary', '0002_lifestyle_values_alter_lifestyle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='lifestyle',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Образ жизни'),
        ),
        migrations.AlterField(
            model_name='lifestyle',
            name='values',
            field=models.FloatField(blank=True, null=True, verbose_name='Коэффициент'),
        ),
    ]
