# Generated by Django 4.2.4 on 2023-09-25 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_body_options_alter_body_arm_chest_and_more'),
        ('diary', '0004_food_consume'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ownwer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
