# Generated by Django 4.2.4 on 2023-09-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_food_ownwer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='ownwer',
            new_name='owner',
        ),
    ]
