# Generated by Django 4.2.4 on 2023-09-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_rename_ownwer_food_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
