# Generated by Django 4.2.4 on 2023-09-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.fitness'),
        ),
    ]
