# Generated by Django 4.2.4 on 2023-08-29 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('chest_girth', models.FloatField(blank=True, null=True)),
                ('arm_chest', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('lower_abdomen', models.FloatField(blank=True, null=True)),
                ('hip_girth', models.FloatField(blank=True, null=True)),
                ('leg_girth', models.FloatField(blank=True, null=True)),
                ('calf_girth', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
