# Generated by Django 4.2.4 on 2023-09-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='body',
            name='arm_chest',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Обхват рук'),
        ),
        migrations.AlterField(
            model_name='body',
            name='calf_girth',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Обхват икр'),
        ),
        migrations.AlterField(
            model_name='body',
            name='chest_girth',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Обхват груди'),
        ),
        migrations.AlterField(
            model_name='body',
            name='hip_girth',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Обхват бедер'),
        ),
        migrations.AlterField(
            model_name='body',
            name='leg_girth',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Обхват ног'),
        ),
        migrations.AlterField(
            model_name='body',
            name='lower_abdomen',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Низ живота'),
        ),
        migrations.AlterField(
            model_name='body',
            name='waist',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Талия'),
        ),
        migrations.AlterField(
            model_name='body',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Вес'),
        ),
    ]
