# Generated by Django 4.2.4 on 2023-08-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='articles/default.jpg', null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='diets',
            name='image',
            field=models.ImageField(upload_to='diets/'),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='image',
            field=models.ImageField(upload_to='recipes/'),
        ),
    ]
