# Generated by Django 4.2.4 on 2023-08-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('food', '0002_alter_articles_image_alter_diets_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='articles/default.jpg', null=True, upload_to='articles/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='topics',
            field=models.ManyToManyField(blank=True, to='food.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='diets',
            name='description',
            field=models.TextField(verbose_name='Описание диеты'),
        ),
        migrations.AlterField(
            model_name='diets',
            name='image',
            field=models.ImageField(upload_to='diets/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='diets',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название диеты'),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='description',
            field=models.TextField(verbose_name='Текст рецепта'),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='image',
            field=models.ImageField(upload_to='recipes/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='ingredients',
            field=models.TextField(verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Тема'),
        ),
        migrations.CreateModel(
            name='RewiewRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.articles')),
            ],
            options={
                'unique_together': {('owner', 'recipe')},
            },
        ),
        migrations.CreateModel(
            name='RewiewArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.articles')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'unique_together': {('owner', 'article')},
            },
        ),
    ]
